name: 'build-sdk'
author: 'Ulf Hallgren <ulf.hallgren@teliacompany.com>'
description: 'Builds Sagemcom SDK'
inputs:
  user:
    version: 'SDK Version'
    required: true
  password:
    sdk_tar: 'The folder where the SDK tar file is stored.'
    required: true
  compiled_sdk_tar:
    description: 'The folder where the compiled SDK is stored.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
