name: Build images for Github actions

# on:
#   release:
#     types: [published]

on:
 push:
   branches: main

jobs:
  build-dev-con-cpp:
    if: false
    name: Build Dev Container cpp image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: connectedhome/hc-devcon-cpp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./devcon-cpp
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
  build_sagem_image:
    name: Build sagem SDK 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: compiled_sdk 
          key: compiled_sdk_key

      - name: Checkout out the repo
        uses: actions/checkout@v3

      - name: Fetch SDK 
        uses: ./.github/actions/ftp-get
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local: sdk
          remote: Telia_Internal/sagemcom/sdk/SDK_F5370E_2022
          
      - name: Fake Build SDK
        run: |
          echo "This is not the sdk" >> compiled_sdk/fake.txt

      # - name: Build SDK 
      #   uses: ./.github/actions/sagemcom/f5370e/build-sdk
      #   with:
      #     sdk_version: SG4T1E100008S
      #     sdk_tar: sdk
      #     compiled_sdk_tar: compiled_sdk

      # - name: Store SDK 
      #   uses: ./.github/actions/ftp-put
      #   with:
      #     user: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local: compiled_sdk
      #     remote: compiled_sdk

  build-dev-con-cpp-sagem:
    name: Build Dev Container cpp sagem image
    runs-on: ubuntu-latest
    needs: [build_sagem_image]

    steps:
      - uses: actions/cache@v3
        with:
          path: compiled_sdk 
          key: compiled_sdk_key

      - name: Checkout out the repo
        uses: actions/checkout@v3

      - name: Check cached file
        run: | 
          echo "Cached data"
          cat compiled_sdk/fake.txt
