name: Build images for Github actions

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build-dev-con-cpp:
    name: Build Dev Con cpp
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: connectedhome/hc-devcon-cpp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./devcon-cpp
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
  build_sagem_sdk:
    name: Build sagem SDK 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v3

      - name: Fetch SDK 
        uses: .github/actions/ftp-get
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local: sdk
          remote: gh_actions/sagemcom/f5370/sdk/SDK_F5370E_2022
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: connectedhome/hc-devcon-cpp

      - name: Build SDK 
        uses: .github/actions/sagemcom/f5370e/build-sdk
        with:
          sdk_version: SG4T1E100008S
          sdk_tar: sdk
          compiled_sdk_tar: compiled_sdk

      - name: Store SDK 
        uses: ./.github/actions/ftp-put
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local: compiled_sdk
          remote: gh_actions/sagemcom/f5370/sdk/SDK_F5370E_2022

  build-dev-con-cpp-sagem:
    name: Build Dev Con cpp sagem
    runs-on: ubuntu-latest
    needs: [build_sagem_sdk,build-dev-con-cpp]

    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v3

      - name: Fetch compiled SDK
        uses: .github/actions/ftp-get
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local: devcon-cpp-sagem
          remote: gh_actions/sagemcom/f5370/sdk/SDK_F5370E_2022

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: connectedhome/hc-devcon-cpp-sagem

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./devcon-cpp-sagem
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

